import json
import sys
import logging
import cherrypy
import threading
import time
import dateutil.parser
from mongo_db import MongoDBAdapter

# Configure logging with DEBUG level


logger = logging.getLogger(__name__)


# ============================================================
# VALIDATION FUNCTIONS
# ============================================================

def check_if_is_a_service(new_service):
    """Validate that the service contains all required fields."""
    required_fields = ['serviceID','name','type','endpoint','last_update']
    require_fields(new_service, required_fields)


def check_if_is_a_device(new_device):
    """Validate that the device contains all required fields."""
    # device_id is autogenerated by DB; require device_name and bedroom_id at minimum
    required_fields = ['device_name', 'bedroom_id']
    require_fields(new_device, required_fields)

def require_fields(payload, required_fields):
    if not all(field in payload for field in required_fields):
        raise cherrypy.HTTPError(400, "Missing required fields in JSON")
# ============================================================
# CATALOG REST SERVICE
# ============================================================

def _load_json_body():
    body = cherrypy.request.body.read()
    try:
        return json.loads(body)
    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON format in request body: {e}")
        raise cherrypy.HTTPError(400, "Invalid JSON format")
    except Exception as e:
        logger.error(f"Unexpected error parsing request body: {e}")
        raise cherrypy.HTTPError(400, "Error parsing request body")


class Catalog:

    exposed = True

    def __init__(self, db_adaptor, cleanup_interval_s=30, service_ttl_s=60):
        self.db = db_adaptor
        self.cleanup_interval_s = cleanup_interval_s
        self.service_ttl_s = service_ttl_s
        self._stop_event = threading.Event()
        self._worker = None

    def start_cleanup_loop(self):
        if self._worker is not None:
            return

        def _loop():
            while not self._stop_event.is_set():
                try:
                    deleted = self.db.delete_stale_services(self.service_ttl_s)
                    if deleted > 0:
                        print(f"Removed {deleted} stale services (ttl={self.service_ttl_s}s)")
                except Exception as e:
                    print(f"Error during cleanup loop: {e}")
                time.sleep(self.cleanup_interval_s)

        self._worker = threading.Thread(target=_loop, daemon=True)
        self._worker.start()

    def stop_cleanup_loop(self):
        self._stop_event.set()
        if self._worker is not None:
            self._worker.join(timeout=10)
            self._worker = None

    # POST METHOD - Create new resources
    def POST(self, *uri, **params):
        """Handle POST requests to add new Services, Devices, or Users."""
        if not uri:
            print("POST request with no endpoint specified")
            raise cherrypy.HTTPError(400, "Endpoint not specified")

        handlers = {
            "addService": self._post_add_service,
            "addDevice": self._post_add_device,
        }
        handler = handlers.get(uri[0])
        if not handler:
            print(f"POST handler not found for endpoint: {uri[0]}")
            raise cherrypy.HTTPError(404, "Endpoint not found")
        return handler()

    def _post_add_service(self):
        """Add a new service to the catalog."""
        try:
            new_service = _load_json_body()
            check_if_is_a_service(new_service)
            success = self.db.insert_service(new_service)

            if success:
                return json.dumps({"status": "success", "message": "Service Added"})

            print(f"Service ID {new_service.get('serviceID')} already exists")
            raise cherrypy.HTTPError(409, "The Service ID already exists")
        except Exception as e:
            print(f"Error in _post_add_service: {e}")
            raise

    def _post_add_device(self):
        """Add a new device to the catalog."""
        new_device = _load_json_body()
        # validate minimal fields (device_name, bedroom_id)
        check_if_is_a_device(new_device)

        device_id = self.db.insert_device(new_device)
        if device_id:
            return json.dumps({"status": "success", "message": "Device Added", "device_id": device_id})
        raise cherrypy.HTTPError(409, "Failed to create device")

    # PUT METHOD - Update existing resources
    def PUT(self, *uri, **params):
        """Handle PUT requests to update Services, Devices, or Users."""
        logger.info(f"PUT method called with uri={uri}, params={params}")
        if not uri:
            print("PUT request with no endpoint specified")
            raise cherrypy.HTTPError(400, "Endpoint not specified")

        handlers = {
            "updateService": self._put_update_service,
            "updateServiceLastUpdate": self._put_update_service_last_update,
            "updateDevice": self._put_update_device,
        }
        handler = handlers.get(uri[0])
        logger.info(f"Looking for handler: {uri[0]}, found: {handler is not None}")
        if not handler:
            print(f"Handler not found for endpoint: {uri[0]}")
            raise cherrypy.HTTPError(404, "Endpoint not found")
        logger.info(f"Calling handler for {uri[0]}")
        return handler()

    def _put_update_service(self):
        """Update an existing service in the catalog."""
        updated_service = _load_json_body()
        check_if_is_a_service(updated_service)

        success = self.db.update_service(updated_service)
        if success:
            return json.dumps({"status": "success", "message": "Service updated"})
        print(f"Update failed for serviceID {updated_service.get('serviceID')}")
        raise cherrypy.HTTPError(404, "The Service ID does not exist")

    def _put_update_service_last_update(self):
        """Update the last_update timestamp of a service."""
        try:
            updated_service = _load_json_body()
            require_fields(updated_service, ['serviceID', 'last_update'])

            success = self.db.update_service_last_update(updated_service['serviceID'], updated_service['last_update'])
            if success:
                return json.dumps({"status": "success", "message": "Service last_update updated"})

            print(f"Update failed for serviceID {updated_service.get('serviceID')} - service not found")
            raise cherrypy.HTTPError(404, "The Service ID does not exist")
        except cherrypy.HTTPError:
            raise
        except Exception as e:
            print(f"Error in _put_update_service_last_update: {e}")
            raise cherrypy.HTTPError(500, "Internal Server Error")

    def _put_update_device(self):
        """Update an existing device in the catalog."""
        updated_device = _load_json_body()
        check_if_is_a_device(updated_device)

        success = self.db.update_device(updated_device)
        if success:
            return json.dumps({"status": "success", "message": "Device updated"})
        raise cherrypy.HTTPError(404, "The Device ID does not exist")


    # DELETE METHOD - Remove resources
    def DELETE(self, *uri, **params):
        """Handle DELETE requests to remove Services, Devices, Users, or Bedrooms."""
        if not uri:
            raise cherrypy.HTTPError(400, "Endpoint not specified")

        handlers = {
            "removeService": self._delete_remove_service,
            "removeDevice": self._delete_remove_device,

        }
        handler = handlers.get(uri[0])
        if not handler:
            raise cherrypy.HTTPError(404, "Endpoint not found")
        return handler(params)

    def _delete_remove_service(self, params):
        """Delete a service by serviceID."""
        service_id = params.get('serviceID')
        if not service_id:
            raise cherrypy.HTTPError(400, "Missing 'serviceID' parameter")

        success = self.db.delete_service(service_id)
        if success:
            return json.dumps({"status": "success", "message": "Service Deleted"})
        raise cherrypy.HTTPError(404, "Service not found")



    def _delete_remove_device(self, params):
        """Delete a device by deviceID."""
        device_id = params.get('deviceID')
        if not device_id:
            raise cherrypy.HTTPError(400, "Missing 'deviceID' parameter")

        success = self.db.delete_device(device_id)
        if success:
            return json.dumps({"status": "success", "message": "Device Deleted"})
        raise cherrypy.HTTPError(404, "Device not found")


    # GET METHOD - Retrieve resources
    def GET(self, *uri, **params):
        """Handle GET requests to retrieve information about Services, Devices, Users, or Bedrooms."""
        logger.info(f"GET method called with uri={uri}, params={params}")
        if not uri:
            print("GET request with no endpoint specified")
            raise cherrypy.HTTPError(400, "Endpoint not specified")

        handlers = {
            "getAllServices": self._get_all_services,
            "getService": self._get_service,
            "getEndpointTimeSeries": self._get_endpoint_Time_series_DB,
            "getEndpointUserService": self._get_endpoint_user_service,
        }
        handler = handlers.get(uri[0])
        if not handler:
            print(f"GET handler not found for endpoint: {uri[0]}")
            raise cherrypy.HTTPError(404, "Endpoint not found")
        return handler(params)

    def _get_endpoint_Time_series_DB(self):
        """Get the endpoint of the TimeSeriesDB service."""
        try:
            endpoint = self.db.get_endpoint_Time_series_DB()
            if endpoint:
                return json.dumps({"status": "success", "endpoint": endpoint})
            print("TimeSeriesDB service not found")
            raise cherrypy.HTTPError(404, "TimeSeriesDB service not found")
        except cherrypy.HTTPError:
            raise
        except Exception as e:
            print(f"Error retrieving TimeSeriesDB endpoint: {e}")
            raise cherrypy.HTTPError(500, "Internal Server Error")

    def _get_endpoint_user_service(self):
        """Get the endpoint of the UserService."""
        try:
            endpoint = self.db.get_endpoint_user_service()
            if endpoint:
                return json.dumps({"status": "success", "endpoint": endpoint})
            print("UserService not found")
            raise cherrypy.HTTPError(404, "UserService not found")
        except cherrypy.HTTPError:
            raise
        except Exception as e:
            print(f"Error retrieving UserService endpoint: {e}")
            raise cherrypy.HTTPError(500, "Internal Server Error")

    def _get_all_services(self, params):
        """Get all services from the catalog (for debugging)."""
        try:
            services = self.db.get_all_services()
            services_json = []
            for service in services:
                service['_id'] = str(service.get('_id', ''))
                services_json.append(service)
            return json.dumps({"status": "success", "count": len(services), "services": services_json})
        except Exception as e:
            print(f"Error retrieving all services: {e}")
            raise cherrypy.HTTPError(500, "Internal Server Error")

    def _get_service(self, params):
        """Get a specific service by serviceID."""
        service_id = params.get('serviceID')
        if not service_id:
            raise cherrypy.HTTPError(400, "Missing 'serviceID' parameter")
        try:
            service = self.db.get_service(service_id)
            if service:
                service['_id'] = str(service.get('_id', ''))
                return json.dumps({"status": "success", "service": service})
            print(f"Service {service_id} not found")
            raise cherrypy.HTTPError(404, f"Service {service_id} not found")
        except cherrypy.HTTPError:
            raise
        except Exception as e:
            print(f"Error retrieving service {service_id}: {e}")
            raise cherrypy.HTTPError(500, "Internal Server Error")

    def _get_check_username(self, params):
        """Check if a username exists in the database."""
        username = params.get('username')
        if not username:
            raise cherrypy.HTTPError(400, "Missing 'username' parameter")
        try:
            exists = self.db.check_user_exists(username)
            return json.dumps({"status": "success", "exists": exists})
        except Exception as e:
            logger.error(f"Error checking username: {e}")
            raise cherrypy.HTTPError(500, "Internal Server Error")

    def _get_devices(self, params):
        """Return list of devices for a given bedroom_id."""
        bedroom_id = params.get('bedroom_id')
        if not bedroom_id:
            raise cherrypy.HTTPError(400, "Missing 'bedroom_id' parameter")
        try:
            devices = self.db.get_devices_by_bedroom(bedroom_id)
            devices_out = []
            for d in devices:
                device_id, device_name, device_type, value = d
                devices_out.append({
                    'device_id': device_id,
                    'device_name': device_name,
                    'device_type': device_type,
                    'value': value,
                })
            return json.dumps({"status": "success", "devices": devices_out})
        except Exception as e:
            logger.error(f"Error retrieving devices for bedroom {bedroom_id}: {e}")
            raise cherrypy.HTTPError(500, "Internal Server Error")


def json_error_page(status, message, traceback, version):
    """Override CherryPy HTTPError to return JSON instead of HTML."""
    cherrypy.response.headers["Content-Type"] = "application/json"
    try:
        status_code = int(status.split(" ")[0])
    except (ValueError, IndexError):
        status_code = 500

    return json.dumps({
        "status": status_code,
        "error": message
    })

if __name__ == "__main__":
    # CherryPy Configuration
    conf = {
        '/': {
            'request.dispatch': cherrypy.dispatch.MethodDispatcher(),
            'tools.sessions.on': True,
        }
    }

    # Load Configuration from JSON
    try:
        with open("conf.json", "r") as f:
            full_conf = json.load(f)
            server_conf = full_conf['server']
            db_conf = full_conf['database']
            cleanup_conf = full_conf.get('service_cleanup', {})
            cleanup_interval_s = cleanup_conf.get('interval_seconds', 30)
            service_ttl_s = cleanup_conf.get('ttl_seconds', 60)
    except FileNotFoundError:
        logger.error("Configuration file 'conf.json' not found")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Error reading conf.json: {e}")
        sys.exit(1)
    try:
        my_db_adaptor = MongoDBAdapter(db_conf)
    except Exception as e:
        logger.error(f"Failed to initialize database connection: {e}")
        sys.exit(1)
    try:
        catalog = Catalog(my_db_adaptor, cleanup_interval_s, service_ttl_s)
        cherrypy.tree.mount(catalog, '/', conf)

        # Configure Server Settings
        cherrypy.config.update({
            'server.socket_port': server_conf['port'],
            'server.socket_host': server_conf['host'],
            'error_page.default': json_error_page
        })

        print(f"Starting Catalog Service on {server_conf['host']}:{server_conf['port']}")
        cherrypy.engine.subscribe('start', catalog.start_cleanup_loop)
        cherrypy.engine.subscribe('stop', catalog.stop_cleanup_loop)
        cherrypy.engine.start()
        cherrypy.engine.block()
    except KeyError as e:
        logger.error(f"Missing server configuration key: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Error starting service: {e}")
        sys.exit(1)
