FROM python:3.12-slim
WORKDIR /app

COPY catalog/requirements.txt ./

RUN pip install -r requirements.txt

COPY catalog /app/catalog
COPY common /app/common

# Make shared packages importable without modifying sys.path
ENV PYTHONPATH=/app
WORKDIR /app/catalog
CMD ["python3", "catalog.py"]
