
POST http://localhost:8080/addService
Content-Type: application/json

{
  "serviceID": "1",
  "name": "Time Shift 001",
  "endpoint": "http://localhost:8080/timeShift",
  "type": "Time Shift",
  "last_update": "2024-06-01T12:00:00Z"
}
###
DELETE http://localhost:8080/removeService?serviceID=Time Shift 001
###

POST http://localhost:8080/addBedroom
Content-Type: application/json

{
  "room_name": "Bedroom 001",
  "password": "123"
}

###
POST http://localhost:8080/addUser
Content-Type: application/json

{
  "username": "User 004",
  "telegram_chat_id": "123456785"
}

###
GET http://localhost:8080/getDatabaseEndpoint

###
GET http://localhost:8080/checkUsername?username=antontino54

###
GET http://localhost:8080/getUserSession?telegram_chat_id=417168004
###
GET http://localhost:8080/checkRoom/?bedroom_id=8&password=2


