services:
  subscriber:
    build: .
    container_name: bettersleep_subscriber
    command: python -u subscriber.py 
    env_file:
      - .env
    restart: unless-stopped

  simulator:
    build: .
    container_name: bettersleep_simulator
    command: python -u simulator.py 
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - subscriber