FROM python:3.12-slim

WORKDIR /service

COPY bed_analytics/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY bed_analytics ./
COPY common ./common

CMD ["python3", "bed_analytics.py"]



