FROM python:3.12-slim

WORKDIR /service

COPY user_service/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY user_service ./
COPY common ./common

CMD ["python3", "user_service.py"]



