FROM python:3.12-slim

WORKDIR /app

COPY user_service/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY user_service /app/user_service
COPY common /app/common

ENV PYTHONPATH=/app
WORKDIR /app/user_service

CMD ["python3", "user_service.py"]



