FROM python:3.12-slim

WORKDIR /service

COPY sleep_cycle_manager/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY sleep_cycle_manager ./
COPY common ./common

CMD ["python3", "sleep_cycle_manager.py"]
