FROM python:3.12-slim

WORKDIR /app

COPY sleep_cycle_manager/requirements.txt ./
RUN pip install -r requirements.txt

COPY sleep_cycle_manager /app/sleep_cycle_manager
COPY common /app/common

ENV PYTHONPATH=/app
WORKDIR /app/sleep_cycle_manager

CMD ["python3", "sleep_cycle_manager.py"]
