FROM python:3.12-slim

WORKDIR /service

COPY time_series/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY time_series ./
COPY common ./common

CMD ["python3", "time_series.py"]
